from __future__ import annotations

import argparse
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

DARK = RGBColor(11, 16, 32)
INK = RGBColor(31, 41, 55)
MUTED = RGBColor(100, 116, 139)
BLUE = RGBColor(37, 99, 235)
CYAN = RGBColor(6, 182, 212)
GREEN = RGBColor(34, 197, 94)
AMBER = RGBColor(245, 158, 11)
RED = RGBColor(239, 68, 68)
WHITE = RGBColor(255, 255, 255)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a Keynote-compatible PPTX guide deck.")
    parser.add_argument("--output", type=Path, default=Path("dist/keynote/threads-auto-poster-keynote.pptx"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    prs = Presentation()
    prs.slide_width = Inches(16)
    prs.slide_height = Inches(9)

    add_cover(prs)
    add_architecture(prs)
    add_process(prs)
    add_program_map(prs)
    add_safety_model(prs)
    add_github_actions(prs)
    add_secret_setup(prs)
    add_operations(prs)

    prs.save(args.output)
    print(f"created {args.output}")
    return 0


def add_cover(prs: Presentation) -> None:
    slide = blank_slide(prs)
    background(slide, DARK)
    add_text(slide, "Threads Auto Poster", 0.8, 0.8, 14.4, 0.7, 42, WHITE, bold=True)
    add_text(slide, "AIはAPIを叩かない。CLIとGitHub Actionsで安全に投稿まで流す。", 0.85, 1.65, 13.8, 0.5, 20, RGBColor(203, 213, 225))
    add_box(slide, "AIはAPIを叩かない", 1.0, 3.0, 3.2, 1.1, CYAN, 22)
    add_box(slide, "標準dry-run", 4.55, 3.0, 3.2, 1.1, GREEN, 22)
    add_box(slide, "--execute時だけ投稿", 8.1, 3.0, 3.2, 1.1, AMBER, 22)
    add_box(slide, "Secretsは非コミット", 11.65, 3.0, 3.2, 1.1, RED, 22)
    add_footer(slide, "Generated by scripts/build_keynote_deck.py — open this PPTX in Apple Keynote")


def add_architecture(prs: Presentation) -> None:
    slide = titled_slide(prs, "1. アーキテクチャ全体像")
    add_box(slide, "Operator\nGitHub UI / CLI", 0.8, 2.1, 2.6, 1.0, BLUE)
    add_box(slide, "AI Agent\nCodex / Claude", 0.8, 4.0, 2.6, 1.0, CYAN)
    add_box(slide, "threads-auto-poster CLI\nvalidate → plan → execute", 5.0, 2.95, 3.6, 1.4, GREEN)
    add_box(slide, "Secrets\n.env / GitHub Secrets", 5.0, 5.25, 3.6, 1.0, AMBER)
    add_box(slide, "Threads API\n/me /threads /threads_publish", 10.5, 2.95, 3.8, 1.4, RED)
    add_box(slide, "Artifacts\nJSON log + Keynote PPTX", 10.5, 5.25, 3.8, 1.0, BLUE)
    arrow(slide, 3.55, 2.6, 4.9, 3.45)
    arrow(slide, 3.55, 4.5, 4.9, 3.65)
    arrow(slide, 8.75, 3.45, 10.35, 3.45)
    arrow(slide, 6.8, 5.2, 6.8, 4.55)
    arrow(slide, 8.75, 4.2, 10.35, 5.5)
    add_footer(slide, "実投稿経路はCLIの--executeに集約。AIはdry-runと資料生成だけを担当。")


def add_process(prs: Presentation) -> None:
    slide = titled_slide(prs, "2. Threads投稿プロセス")
    steps = [("投稿文を読む", BLUE), ("500文字検証", CYAN), ("dry-run判定", GREEN), ("container作成", AMBER), ("threads_publish", RED), ("結果JSON保存", BLUE)]
    x = 0.7
    for label, color in steps:
        add_box(slide, label, x, 3.3, 2.1, 1.0, color, 17)
        if x < 12:
            arrow(slide, x + 2.15, 3.8, x + 2.75, 3.8)
        x += 2.55
    add_bullets(slide, ["API呼び出しは2段階: /threadsでコンテナIDを作り、/threads_publishで公開します。", "dry-runではThreads APIに接続せず、投稿予定と文字数だけをJSON化します。", "失敗時もartifactに構造化ログを残すので、CIから原因を追えます。"], 1.0, 5.45, 14.0, 1.8)
    add_footer(slide, "Process view")


def add_program_map(prs: Presentation) -> None:
    slide = titled_slide(prs, "3. プログラム構成")
    add_box(slide, "cli.py\nargparse / safety gate", 0.9, 2.0, 3.2, 1.0, BLUE)
    add_box(slide, "config.py\n.env / Secrets loading", 4.6, 2.0, 3.2, 1.0, CYAN)
    add_box(slide, "post_runner.py\nload / validate / result", 8.3, 2.0, 3.2, 1.0, GREEN)
    add_box(slide, "threads_client.py\nThreads API client", 12.0, 2.0, 3.2, 1.0, AMBER)
    add_bullets(slide, ["CLIは入力・安全判定・結果出力だけを担当し、ネットワーク処理はclientに分離します。", "post_runnerはテストしやすい純粋ロジック中心で、dry-runならclientを要求しません。", "threads_clientはBearer tokenをヘッダーに入れますが、ログにはtokenを出しません。", "scripts/build_keynote_deck.pyがこのKeynote互換PPTXを再生成します。"], 1.0, 4.0, 14.0, 2.5)
    add_footer(slide, "Program map")


def add_safety_model(prs: Presentation) -> None:
    slide = titled_slide(prs, "4. 安全モデル")
    add_box(slide, "Default\ndry-run", 1.0, 2.2, 3.0, 1.1, GREEN, 24)
    add_box(slide, "Human approval\n--execute", 4.8, 2.2, 3.0, 1.1, AMBER, 24)
    add_box(slide, "Secrets\n.env / GitHub Secrets", 8.6, 2.2, 3.0, 1.1, BLUE, 24)
    add_box(slide, "No secret logs\nredacted output", 12.4, 2.2, 2.8, 1.1, RED, 22)
    add_bullets(slide, ["AI作業ではmake dry-run / make test / make deckのみを標準許可します。", "GitHub Actionsの実投稿workflowも標準dry-runです。", "実投稿時はdry_run=falseに加えてconfirm_publish=PUBLISHが必要です。", "投稿結果はpost_idとcontainer_idだけを保存し、tokenは保存しません。"], 1.0, 4.3, 14.0, 2.4)
    add_footer(slide, "Safety model")


def add_github_actions(prs: Presentation) -> None:
    slide = titled_slide(prs, "5. GitHub Actions")
    add_box(slide, "CI\nruff + pytest + deck", 1.0, 2.1, 3.6, 1.3, BLUE)
    add_box(slide, "Threads Publish\nmanual workflow", 6.1, 2.1, 3.6, 1.3, GREEN)
    add_box(slide, "Scheduled Dry Run\nqueue validation", 11.2, 2.1, 3.6, 1.3, CYAN)
    add_bullets(slide, ["CIはpush / pull_request / workflow_dispatchで動き、Keynote互換PPTXをartifact化します。", "Threads Publishは手動実行で、標準ではAPIを叩かないdry-runです。", "スケジュールworkflowは投稿キューを検証し、実投稿はSecrets側の明示設定が必要です。", "upload-artifact v4でログとPPTXを保存します。"], 1.0, 4.2, 14.0, 2.6)
    add_footer(slide, "CI/CD")


def add_secret_setup(prs: Presentation) -> None:
    slide = titled_slide(prs, "6. Secrets設定")
    add_bullets(slide, ["THREADS_ACCESS_TOKEN: 実投稿用のThreads User Access Token。", "THREADS_USER_ID: 投稿対象ユーザーID。未設定時はCLIが/meで解決可能。", "THREADS_APP_ID / THREADS_APP_SECRET: token交換・更新系で使用。", "THREADS_DRY_RUN=true: 安全側の標準値。falseは人間が明示するときだけ。", "実値はGitHub Secretsかローカル.envにのみ保存し、READMEやissueに書かない。"], 1.0, 1.8, 14.0, 4.0)
    add_box(slide, "Production requires Meta app + permissions + valid token + posting limits control", 1.0, 6.5, 14.0, 0.9, AMBER, 22)
    add_footer(slide, "Secrets setup")


def add_operations(prs: Presentation) -> None:
    slide = titled_slide(prs, "7. 運用チェックリスト")
    add_bullets(slide, ["まずCI artifactのKeynote資料を開き、構成と安全ゲートを確認します。", "GitHub Secretsを設定後、Threads Publish workflowをdry-run=trueで実行します。", "dry-run artifactの投稿予定を確認し、問題がなければdry_run=false / confirm_publish=PUBLISH。", "tokenは期限前にrefresh-tokenを人間操作で実行し、GitHub Secretsを更新します。", "投稿上限やMeta側の審査状態を定期的に確認します。"], 1.0, 1.8, 14.0, 4.3)
    add_box(slide, "最重要: AIはAPIを叩かず、実投稿は人間の明示操作だけ", 1.0, 6.5, 14.0, 0.9, RED, 24)
    add_footer(slide, "Operations")


def blank_slide(prs: Presentation):
    return prs.slides.add_slide(prs.slide_layouts[6])


def titled_slide(prs: Presentation, title: str):
    slide = blank_slide(prs)
    background(slide, WHITE)
    add_text(slide, title, 0.7, 0.45, 14.5, 0.5, 30, DARK, bold=True)
    line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.7), Inches(1.15), Inches(14.6), Inches(0.04))
    line.fill.solid()
    line.fill.fore_color.rgb = RGBColor(226, 232, 240)
    line.line.fill.background()
    return slide


def background(slide, color: RGBColor) -> None:
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def add_box(slide, text: str, x: float, y: float, w: float, h: float, color: RGBColor, size: int = 18):
    shape = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.color.rgb = color
    frame = shape.text_frame
    frame.clear()
    frame.word_wrap = True
    p = frame.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run()
    run.text = text
    run.font.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = WHITE
    return shape


def add_text(slide, text: str, x: float, y: float, w: float, h: float, size: int, color: RGBColor, *, bold: bool = False):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    frame = box.text_frame
    frame.clear()
    frame.word_wrap = True
    p = frame.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return box


def add_bullets(slide, bullets: list[str], x: float, y: float, w: float, h: float) -> None:
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    frame = box.text_frame
    frame.clear()
    frame.word_wrap = True
    for idx, text in enumerate(bullets):
        p = frame.paragraphs[0] if idx == 0 else frame.add_paragraph()
        p.text = f"• {text}"
        p.font.size = Pt(18)
        p.font.color.rgb = INK
        p.space_after = Pt(8)


def arrow(slide, x1: float, y1: float, x2: float, y2: float) -> None:
    connector = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x1), Inches(y1), Inches(x2), Inches(y2))
    connector.line.color.rgb = MUTED
    connector.line.width = Pt(2)


def add_footer(slide, text: str) -> None:
    add_text(slide, text, 0.75, 8.25, 14.5, 0.3, 11, MUTED)


if __name__ == "__main__":
    raise SystemExit(main())
